name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install dependencies
        run: flutter pub get

      - name: Set iOS deployment target to 13.0
        run: |
          sed -i '' 's/platform :ios, '12.0'/platform :ios, '13.0'/' ios/Podfile || true
          echo "Updated iOS deployment target to 13.0"

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install --repo-update

      - name: Build iOS App
        run: flutter build ios --release --no-codesign

      - name: Prepare IPA packaging
        run: mkdir -p Payload && mv Runner.app Payload
        working-directory: build/ios/iphoneos

      - name: Create IPA file
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"
